hdykokd/obsidian-vertical-tabs-view

- src/main.ts
- src/setting.ts
- src/util/setting.ts
- src/view.ts
> View position

- src/main.ts
- src/setting.ts
- src/view.ts
- styles.css
> feat: show pin icon

- src/view.ts
> feat: show views other than markdown type.

- src/main.ts
> fix: add command 'show-vertical-tabs-view' to global context

- src/main.ts
https://github.com/hdykokd/obsidian-vertical-tabs-view/pull/19
> fix command id

- src/constants.ts
- src/main.ts
- src/setting.ts
- src/util/view.ts
- src/view.test.ts
- src/view.ts
> somes fixes for tab icon 

- src/view.ts
> feat: detect new tab

- package.json
- pnpm-lock.yaml
- src/main.ts
- src/util/leaf.ts
- src/view.ts
- styles.css
- tsconfig.json
#26
- new feature: sortable tabs using sortablejs
- add command: `Cycle Previous Tab`
- add command: `Cycle Next Tab`
> feat: sortable

- src/view.ts
- styles.css
> fix: increase clickable button styles

- src/view.ts
https://github.com/hdykokd/obsidian-vertical-tabs-view/issues/21#issuecomment-1632741251 should be resolved.
> fix: fix issue where scrolling resets to top

- src/view.ts
#32 should resolved probably....
> fix: unable to scroll on mobile

- src/view.ts
> perf: use iterateRootLeaves

- src/util/leaf.ts
This could cause sorting to behave strangely.
#34
> remove hack to make it ready for input

- esbuild.config.mjs
- package.json
- pnpm-lock.yaml
- src/components/Tabs.svelte
- src/main.ts
- src/setting.ts
- src/store.ts
- src/types.ts
- src/util/leaf.ts
- src/util/view.ts
- src/view.test.ts
- src/view.ts
- tsconfig.json
> use Svelte

- src/components/Tabs.svelte
- src/view.ts
> fix a scrolling bug

- styles.css
#39 
https://docs.obsidian.md/Reference/CSS+variables/Components/Tabs
> fix: use --tab-text-color-focused-active-current for the focused tab color

- src/components/Tabs.svelte
- src/setting.ts
> feat: Add the option to be able to hide the directory

- src/components/Tabs.svelte
- src/setting.ts
- styles.css
> feat: add showCloseIcon option

- package.json
- pnpm-lock.yaml
- src/components/Tabs.svelte
- styles.css
close #44, #52 
https://docs.obsidian.md/Plugins/User+interface/Context+menus
Obsidian's plugin system is really powerful...
> feat: use Obsidian's Context menu

- styles.css
> fix: set tab text color to match default tab

- src/components/Tabs.svelte
- styles.css
> fix: add block for scroll magin on mobile

- src/components/Tabs.svelte
- styles.css
> fix: hide cloned item when sorting except on desktop

- src/view.ts
> fix: updating view on 'active-leaf-change' break sorting

- src/components/Tabs.svelte
- src/main.ts
- styles.css
> feat: Select multiple tabs
